apiVersion: v1
kind: Service
metadata:
  name: money-bot-svc
  namespace: money-bot
spec:
  type: LoadBalancer
  selector:
    app: money-bot
  ports:
    - port: 32121
      targetPort: 32121
      # nodePort: 31212
